#!/bin/bash

source ./utils.sh
unset force quiet

force=0
quiet=0
while [ -n "$1" ]; do
	case "$1" in
		-f|--force) force=1 ;;
		-q|--quiet) quiet=1 ;;
		*)
				echo "$1 is not an option, exiting..."
				exit 1
		;;
	esac
	shift
done


if [ ! -d $HOME/scripts ]; then
	mkdir -p $HOME/scripts >/dev/null
	
	if [ ! -d $HOME/scripts ]; then
		blurb "Failed to create directory '$HOME/scripts'"
		exit 1
	fi
	
	blurb "Created directory '$HOME/scripts'"
fi

if [ -d $HOME/scripts/stools ]; then
	blurb -n "Clearing out the old stuff."
	rm -rf $HOME/scripts/stools >/dev/null
	blurb " Done."
fi

blurb -n "Downloading, this could take a minute."
wget -qN https://github.com/the-ransum/stools/archive/refs/heads/main.zip -O /tmp/stools.zip
blurb " Done."


blurb -n "Unzipping..."
unzip -q -j /tmp/stools.zip -d $HOME/scripts/stools
blurb " Done."


require_refresh=0
#if [[ ":$PATH:" != *"$HOME/scripts/stools/bin"* ]]; the
if ! grep -q "\$HOME/scripts/stools/bin" $HOME/.bashrc; then
	blurb -n "Adding $HOME/scripts/stools/bin to path."
	blurb 'export PATH="$PATH:$HOME/scripts/stools/bin"' >> $HOME/.bashrc
	blurb " Done."
	require_refresh=1
fi

blurb -n "Cleaning out the garbage."
rm -f /tmp/stools.zip >/dev/null
blurb " Done."


blurb "Install Complete."
blurb ""
if [ $require_refresh -eq 1 ]; then
	blurb -e "\033[0;33mTo finalize the install, please refresh your terminal or use 'source ~/.bashrc' to refresh.\033[0m"
fi
blurb ""
blurb "To view the scripts use the following 'stools --list'."
