#!/bin/bash

# Requires a variable $quiet to be set to either 0/1 for 
# 0 - quiet mode
# 1 - verbose mode
function blurb {
	if [ $quiet -eq 0 ]; then
		echo "$@"
	fi
}

# Not the cleanest way to nuke the old files, but it works.
if [ "$0" == "/tmp"* ]; then
	cp -f "$0" /tmp/stools
	chmod 755 /tmp/stools
	/tmp/stools
	exit 0
fi

echo "Removing PATH from .bashrc profile."
# Strip the path from .bashrc
sed -e 's/^.*PATH="\$PATH:.*\/stools\/bin.*".*$//g' -i $HOME/.bashrc

# Remove extracted repository from home directory
echo "Nuking repository in '$HOME/scripts/stools'."
if [ -d $HOME/scripts/stools ]; then
	rm -rf $HOME/scripts/stools
fi

echo "Uninstall complete."
echo ""
echo -e "\033[0;33mTo finalize the uninstallation, please refresh your terminal or use 'source ~/.bashrc' to refresh.\033[0m"

# Remove script itself 
rm -- "$0"